const menuBtn=document.getElementById('menuBtn');const nav=document.getElementById('navbar');
menuBtn?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));});
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuBtn?.setAttribute('aria-expanded','false');}));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const sectionLinks=[...document.querySelectorAll('#navbar a')];const sections=[...document.querySelectorAll('main section[id]')];
window.addEventListener('scroll',()=>{let current='home';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)current=s.id});sectionLinks.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});
document.getElementById('year').textContent=new Date().getFullYear();
function n(id){const v=parseFloat(document.getElementById(id).value);return Number.isFinite(v)&&v>0?v:null}
const show=(id,text)=>document.getElementById(id).textContent=text;
document.getElementById('ohmsBtn')?.addEventListener('click',()=>{let V=n('ohmsV'),I=n('ohmsI'),R=n('ohmsR'),P=n('ohmsP');let count=[V,I,R,P].filter(Boolean).length;if(count<2){show('ohmsResult','Enter at least two positive values.');return}for(let x=0;x<3;x++){if(V&&I){R??=V/I;P??=V*I}if(V&&R){I??=V/R;P??=V*V/R}if(V&&P){I??=P/V;R??=V*V/P}if(I&&R){V??=I*R;P??=I*I*R}if(I&&P){V??=P/I;R??=P/(I*I)}if(R&&P){V??=Math.sqrt(P*R);I??=Math.sqrt(P/R)}}if([V,I,R,P].some(v=>!Number.isFinite(v))){show('ohmsResult','Those values cannot form a valid circuit solution.');return}show('ohmsResult',`V ${V.toFixed(2)} V · I ${I.toFixed(2)} A · R ${R.toFixed(2)} Ω · P ${P.toFixed(2)} W`)});
document.getElementById('cableBtn')?.addEventListener('click',()=>{const kw=n('loadKw'),len=n('lengthM'),phase=document.getElementById('phase').value;if(!kw||!len){show('cableResult','Enter load and route length.');return}const voltage=phase==='single'?240:415,pf=.85,I=phase==='single'?kw*1000/(voltage*pf):kw*1000/(Math.sqrt(3)*voltage*pf);const sizes=[[1.5,16],[2.5,22],[4,30],[6,38],[10,52],[16,69],[25,91],[35,111],[50,133],[70,169],[95,205],[120,237]];const size=(sizes.find(x=>x[1]>=I)||sizes.at(-1))[0];const drop=(I*len*4.4/1000)/voltage*100;show('cableResult',`Design current ${I.toFixed(2)} A · reference conductor ${size} mm² · estimated drop ${drop.toFixed(2)}%`) });
document.getElementById('pfBtn')?.addEventListener('click',()=>{const kw=n('pfKw'),pf1=n('pf1'),pf2=n('pf2');if(!kw||!pf1||!pf2||pf1>=1||pf2>1){show('pfResult','Enter valid power and PF values between 0 and 1.');return}const kvar=kw*(Math.tan(Math.acos(pf1))-Math.tan(Math.acos(pf2)));show('pfResult',`Estimated capacitor bank ${Math.max(0,kvar).toFixed(2)} kVAR · initial angle ${(Math.acos(pf1)*180/Math.PI).toFixed(1)}° · target ${(Math.acos(pf2)*180/Math.PI).toFixed(1)}°`) });
